### ISSUE TITLE
missing closing } in function 

### ISSUE THREAD

**Issue by FritsOV** [FatBeard/vbus-arduino-library#15]
Hello,

in function vBusRead()

the following code:

          if (Bufferlength < 20)
          {
            lastTimeTimer = millis();
            Bufferlength = 0;
          }
          else                                                       // <----- missing { 
                 stop = true;
        }

Please correct cpp file.

**Comment by FatBeard** [comment]
Hi. I'm not sure it's requested. Its a one line statement after the if and it compiles. Are you seeing an issue?

**Comment by FritsOV** [comment]
Yes, i got a stackdump on my esp32. connecting to vbus/lan with an Resol MX. 
putting some serial prints in the code shows me that it looks like there is never a way out of the first while  loop.  in the vBusRead()

**Comment by FatBeard** [comment]
Cool. It's working for me on an arduino. But if you raise a pr I'll merge it.

**Comment by FatBeard** [comment]
Hi FritsOV, I've preliminarily ported this to esphome, see the newly attached new files in source if you're interested
