### ISSUE TITLE
Vbus esp32

### ISSUE THREAD

**Issue by hansdeweerd** [FatBeard/vbus-arduino-library#17]
Is there a way to make this work on a esp32? I am not been able to do it.

**Comment by FatBeard** [comment]
I suspect it’s got to do with the timerInterval value in the .h file. Set it to something bigger than zero and it may sort out your problem. Also I’ve checked in recently a rough custom component for esphome. This may suit your requirement. See the resol files. When I have time I’ll tidy things up but they work fine at the moment.
