### ISSUE TITLE
Testing needed

### ISSUE THREAD

**Issue by alfredosola** [FatBeard/vbus-arduino-library#7]
Hello,

I have added further CRC tests, now testing all the frames and a little bit of code cleanup.

Before making a PR I think it would be wise if someone else could do some testing.

The fork is at https://github.com/alfredosola/vbus-arduino-library

Thanks.

**Comment by FatBeard** [comment]
Thanks Alfred. Great feature. I'll try and test over the weekend. Free time is tight at the moment. Will let you know.

**Comment by FatBeard** [comment]
Hi, I installed this tonight. Seems like it's working. I'll let it run for 24 hours and see how it runs, just to make sure.

**Comment by FatBeard** [comment]
Hey. This code is stable for me. Do you want to go ahead and raise the pr?

Thanks again.

**Comment by alfredosola** [comment]
PR raised.
